# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: dispatch

# The runtime the application uses.
type: "python:3.8"

variables:
  env:
    # XXX: dma Not sure if this env var is used anywhere
    DISPATCH_CONF: "/etc/dispatch"
    DISPATCH_BUILD: "develop"

# The build-time dependencies of the app.
dependencies:
  nodejs:
    yarn: "*"

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
      unset NPM_CONFIG_PREFIX
      export NVM_DIR="$PLATFORM_APP_DIR/.nvm"
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm current
      nvm install 12.16.1
      set -eux
      pip install --upgrade setuptools wheel
      pip install --upgrade pip
      pip install -r requirements-base.txt
      pip install -r requirements-dev.txt
      python setup.py bdist_wheel
      pip install dist/*.whl
    deploy: |
      dispatch database init

# The size of the persistent disk of the application (in MB).
disk: 1024

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
#relationships:
#    database: "db:postgresql"

# The configuration of app when it is exposed to the web.
web:
    commands:
      start: "dispatch server start dispatch.main:app --host=0.0.0.0 --port=$PORT"

mounts:
    tmp:
        source: local
        source_path: tmp
    logs:
        source: local
        source_path: logs
